// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Query struct {
}

type Task struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
}
