package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/Joshua-Pok/task-orchestrator/internal/gql/generated"
	"github.com/Joshua-Pok/task-orchestrator/internal/task"
	"github.com/google/uuid"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input *generated.CreateTaskInput) (*generated.Task, error) {
	id := uuid.New()

	r.Store.Add(task.Task{
		ID:    id,
		Title: input.Title,
	})

	return &generated.Task{
		ID:    id.String(),
		Title: input.Title,
	}, nil

}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*generated.Task, error) {
	tasks := r.Store.List()

	var result []*generated.Task

	for _, t := range tasks {
		result = append(result, &generated.Task{
			ID:     t.ID.String(),
			Title:  t.Title,
			Status: t.Status,
		})
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
