package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/Joshua-Pok/task-orchestrator/internal/gql/generated"
	"github.com/Joshua-Pok/task-orchestrator/internal/task"
	"github.com/google/uuid"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input *generated.CreateTaskInput) (*generated.Task, error) {
	id := uuid.New()

	r.Store.Add(task.Task{
		ID:    id,
		Title: input.Title,
	})

	return &generated.Task{
		ID:    id.String(),
		Title: input.Title,
	}, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*generated.Task, error) {
	tasks := r.Store.List()

	var result []*generated.Task

	for _, t := range tasks {
		result = append(result, &generated.Task{
			ID:     t.ID.String(),
			Title:  t.Title,
			Status: t.Status,
		})
	}

	return result, nil
}

// TaskAdded is the resolver for the taskAdded field.
func (r *subscriptionResolver) TaskAdded(ctx context.Context) (<-chan *generated.Task, error) {
	ch := r.Store.Subscribe() // acquire internal channel
	graphqlCh := make(chan *generated.Task, 1)

	//start background goroutine
	go func() {
		defer close(graphqlCh)
		for {
			select{
			case t := <- ch:
			graphqlCh <- &generated.Task{
					ID: t.ID.String()
					Title: t.Title,
				}
			case <-ctx.Done(): //client disconnect
				return

			}
		}

	}()


	return graphqlCh, nil

}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
