package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/Joshua-Pok/task-orchestrator/internal/gql/generated"
)

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*generated.Task, error) {
	tasks := r.Store.List()

	var result []*generated.Task

	for _, t := range tasks {
		result = append(result, &generated.Task{
			ID:     t.ID.String(),
			Title:  t.Title,
			Status: t.Status,
		})
	}

	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
